### ISSUE TITLE
sonali ICD

### ISSUE THREAD

**Issue by austinbean** [austinbean/bpci#10]
@mollycandon 

Here (or somewhere nearby):  

`- gen bipolar = (icd9 == 296 | icd9== 29601 | icd9==29602 | icd9==29603 | icd==29604 | icd9==296
> 05 | icd9==29606 | icd9==2964 | icd9==29641 | icd9==29642 | icd9==29643 | icd9==29644 | icd9==
> 29645 | icd9==29646 | icd9==2965 | icd9==29651 | icd9==29652 | icd9==29653 | icd9==29654 | icd
> 9==29655 | icd9==29656 | icd9==2966 | icd9==29661 | icd9==29662 | icd9==29663 | icd9==29664 | 
> icd9==29665 | icd9==29666 | icd9==2967 | icd9==2968)`

You have this problem:
`icd ambiguous abbreviation`

I am not totally sure what Stata is complaining about b/c all of your uses of "icd" which I can see are qualified w/ a number.

At this point in the file your data contain the following variables w/ the letters "icd" in them:

princ_icd9_code 
other_icd9_code_1 
other_icd9_code_2 
other_icd9_code_3 
other_icd9_code_4 
other_icd9_code_5 
other_icd9_code_6 
other_icd9_code_7 
other_icd9_code_8 
other_icd9_code_9 
other_icd9_code_10 
other_icd9_code_11 
other_icd9_code_12 
other_icd9_code_13 
other_icd9_code_14 
other_icd9_code_15 
other_icd9_code_16 
other_icd9_code_17 
other_icd9_code_18 
other_icd9_code_19 
other_icd9_code_20 
other_icd9_code_21 
other_icd9_code_22 
other_icd9_code_23 
other_icd9_code_24 
icd9 
icd10

Another possible (but unlikely) issue is that there are Stata commands named `icd9` and `icd10`.  I don't think this is causing the issue but maybe give them different names??

I posted the log file if that helps.

**Comment by mollycandon** [comment]
﻿Found it. That was a dumb error—sorry about that.

From: Austin Bean ***@***.***>
Date: Thursday, April 15, 2021 at 2:37 PM
To: austinbean/bpci ***@***.***>
Cc: mollycandon ***@***.***>, Mention ***@***.***>
Subject: [austinbean/bpci] sonali ICD (#10)

@mollycandon<https://github.com/mollycandon>

Here (or somewhere nearby):

`- gen bipolar = (icd9 == 296 | icd9== 29601 | icd9==29602 | icd9==29603 | icd==29604 | icd9==296

05 | icd9==29606 | icd9==2964 | icd9==29641 | icd9==29642 | icd9==29643 | icd9==29644 | icd9==
29645 | icd9==29646 | icd9==2965 | icd9==29651 | icd9==29652 | icd9==29653 | icd9==29654 | icd
9==29655 | icd9==29656 | icd9==2966 | icd9==29661 | icd9==29662 | icd9==29663 | icd9==29664 |
icd9==29665 | icd9==29666 | icd9==2967 | icd9==2968)`

You have this problem:
icd ambiguous abbreviation

I am not totally sure what Stata is complaining about b/c all of your uses of "icd" which I can see are qualified w/ a number.

At this point in the file your data contain the following variables w/ the letters "icd" in them:

princ_icd9_code
other_icd9_code_1
other_icd9_code_2
other_icd9_code_3
other_icd9_code_4
other_icd9_code_5
other_icd9_code_6
other_icd9_code_7
other_icd9_code_8
other_icd9_code_9
other_icd9_code_10
other_icd9_code_11
other_icd9_code_12
other_icd9_code_13
other_icd9_code_14
other_icd9_code_15
other_icd9_code_16
other_icd9_code_17
other_icd9_code_18
other_icd9_code_19
other_icd9_code_20
other_icd9_code_21
other_icd9_code_22
other_icd9_code_23
other_icd9_code_24
icd9
icd10

Another possible (but unlikely) issue is that there are Stata commands named icd9 and icd10. I don't think this is causing the issue but maybe give them different names??

I posted the log file if that helps.

**Comment by mollycandon** [comment]
closing to keep analyses separate
