### ISSUE TITLE
psych_ind

### ISSUE THREAD

**Issue by austinbean** [austinbean/bpci#11]
@mollycandon 

```
replace psychhosp=1 if inlist(fac_psych_ind, "A", "X", "(A)", "(X)")
type mismatch


. tab fac_psych_ind

FAC_PSYCH_I |
         ND |      Freq.     Percent        Cum.
------------+-----------------------------------
          0 |      3,277       25.54       25.54
          1 |      9,555       74.46      100.00
------------+-----------------------------------
      Total |     12,832      100.00

```

That's for 2010.  

For 2015 (for example) you have:

```
. tab FAC_PSYCH_IND

FAC_PSYCH_I |
         ND |      Freq.     Percent        Cum.
------------+-----------------------------------
          X |    155,513      100.00      100.00
------------+-----------------------------------
      Total |    155,513      100.00

```

You may want to `tostring` in 2010 or write for two cases?

**Comment by mollycandon** [comment]
Added a tostring command for 2010 and “1” to the psych hosp inlist command! Thank you!!

From: Austin Bean ***@***.***>
Date: Thursday, April 15, 2021 at 6:18 PM
To: austinbean/bpci ***@***.***>
Cc: mollycandon ***@***.***>, Mention ***@***.***>
Subject: [austinbean/bpci] psych_ind (#11)

@mollycandon<https://github.com/mollycandon>

replace psychhosp=1 if inlist(fac_psych_ind, "A", "X", "(A)", "(X)")

type mismatch





. tab fac_psych_ind



FAC_PSYCH_I |

         ND |      Freq.     Percent        Cum.

------------+-----------------------------------

          0 |      3,277       25.54       25.54

          1 |      9,555       74.46      100.00

------------+-----------------------------------

      Total |     12,832      100.00



That's for 2010.

For 2015 (for example) you have:

. tab FAC_PSYCH_IND



FAC_PSYCH_I |

         ND |      Freq.     Percent        Cum.

------------+-----------------------------------

          X |    155,513      100.00      100.00

------------+-----------------------------------

      Total |    155,513      100.00



You may want to tostring in 2010 or write for two cases?

**Comment by mollycandon** [comment]
closing to keep analyses separate
