### ISSUE TITLE
no if allowed w/ tostring

### ISSUE THREAD

**Issue by austinbean** [austinbean/bpci#13]
@mollycandon 

`tostring fac_psych_ind if year == 2010, replace`
`if not allowed`

**Comment by austinbean** [comment]
I am trying this instead:

`if nm == 2010 {`
`	tostring fac_psych_ind , replace`
`}`

Seems to work.  But now there is another error.

**Comment by mollycandon** [comment]
Holy shit this is handy. I had no idea you could start commands with an if statement!

Can’t thank you enough for dealing with all these errors. Much appreciated.

From: Austin Bean ***@***.***>
Date: Saturday, April 17, 2021 at 12:00 PM
To: austinbean/bpci ***@***.***>
Cc: mollycandon ***@***.***>, Mention ***@***.***>
Subject: Re: [austinbean/bpci] no if allowed w/ tostring (#13)

I am trying this instead:

if nm' == 2010 { tostring fac_psych_ind , replace }`

Seems to work. But now there is another error.
