### ISSUE TITLE
ethnicity variable type

### ISSUE THREAD

**Issue by austinbean** [austinbean/bpci#14]
@mollycandon 

`- replace racecat=3 if ethnicity==1`
`type mismatch`

`ethnicity` is str1.

Maybe destring it first.

**Comment by mollycandon** [comment]
Destringed.

From: Austin Bean ***@***.***>
Date: Saturday, April 17, 2021 at 12:08 PM
To: austinbean/bpci ***@***.***>
Cc: mollycandon ***@***.***>, Mention ***@***.***>
Subject: [austinbean/bpci] ethnicity variable type (#14)

@mollycandon<https://github.com/mollycandon>

- replace racecat=3 if ethnicity==1
type mismatch

ethnicity is str1.

Maybe destring it first.
