### ISSUE TITLE
nrace not found

### ISSUE THREAD

**Issue by austinbean** [austinbean/bpci#16]
@mollycandon 
latest:
`table nrace, c(m schizophrenia sem schizophrenia) `
`variable nrace not found`

You meant (??) `race` or  `racecat` ?

**Comment by mollycandon** [comment]
My bad—I copy/pasted Olivia’s code and she called it racecat not nrace. Updated Sonali’s file.

From: Austin Bean ***@***.***>
Date: Saturday, April 17, 2021 at 6:19 PM
To: austinbean/bpci ***@***.***>
Cc: mollycandon ***@***.***>, Mention ***@***.***>
Subject: [austinbean/bpci] nrace not found (#16)

@mollycandon<https://github.com/mollycandon>
latest:
table nrace, c(m schizophrenia sem schizophrenia)
variable nrace not found

You meant (??) race or racecat ?

**Comment by mollycandon** [comment]
will set up separate folder to keep the schizophrenia analysis separate from Olivia's. planning to table it until Olivia's analysis is done!
