### ISSUE TITLE
error in factor variable

### ISSUE THREAD

**Issue by austinbean** [austinbean/bpci#7]
@mollycandon and @odirienz 

`year` is a string var.  This is around line 237.  See the log file.   

Also I added a long list of all of the variables in the data (in current_error.txt).  I think many of them are not used for this analysis?  (Some are individual level corresponding to whoever's observation was used to create the hospital record, but they play no role here.)  Many can safely be dropped and the analysis file will occupy less room in memory and this may run faster.

**Comment by mollycandon** [comment]
Hey thanks Austin! I’ll update accordingly tomorrow.
________________________________
From: Austin Bean ***@***.***>
Sent: Friday, April 9, 2021 6:59 PM
To: austinbean/bpci
Cc: mollycandon; Mention
Subject: [austinbean/bpci] error in factor variable (#7)


@mollycandon<https://github.com/mollycandon> and @odirienz<https://github.com/odirienz>

year is a string var. This is around line 237. See the log file.

Also I added a long list of all of the variables in the data. I think many of them are not used for this analysis? (Some are individual level corresponding to whoever's observation was used to create the hospital record, but they play no role here.) Many can safely be dropped and the analysis file will occupy less room in memory and this may run faster.
